# Generated by Django 4.0.6 on 2022-08-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_card_receipt_thirdparty_transaction_wallet_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction'),
        ),
    ]
