# Generated by Django 4.0.6 on 2022-08-07 14:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_receipt_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='account_pin',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='CVV_Security_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='card',
            name='issuer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_term',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='pay_due_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.thirdparty'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='bonus_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_a', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_b', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_c', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_ref',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_b', to='wallet.customer'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_a', to='wallet.customer'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcation_b', to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='date_of_reward',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='account',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='transaction_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
