# Generated by Django 4.0.6 on 2022-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_account_account_type_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('K', 'Shilling'), ('$', 'Dollar'), ('EU', 'Euros')], max_length=15, null=True),
        ),
    ]
