# Generated by Django 4.0.6 on 2022-08-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('C', 'Credit card'), ('D', 'Debit card')], max_length=25, null=True),
        ),
    ]
